// Generated by https://quicktype.io

export interface DividaResponse {
  nome: string;
  'posicao-funcao': string;
  'tempo-de-clube': string;
  'valor-a-receber': string;
}

export interface Divida {
  nome: string;
  posicaoFuncao: string;
  tempoDeClube: string;
  valorAReceber: string;
}
